title: Raz Rotenberg
email: raz.rotenberg@gmail.com
description: Hi! I'm Raz. I'm a programmer, but I have plenty more things that I find interest in. Get in touch! e-mail me.

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - _pages/hello.md
  - _pages/about.md
  - _pages/articles.md
  - _pages/projects.md
  - _pages/music.md

include:
  _pages

collections:
  projects:
    output: true
